openapi: 3.0.0
info:
  title: Mouse
openapi: 3.0.0
info:
  title: Mouse Cursor INF Generator
  description: API for generating .inf files for custom mouse cursors.
  version: 1.0.0

paths:
  /generateInf:
    post:
      summary: Generate INF file
      description: Generates an INF file for custom mouse cursors.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                schemeName:
                  type: string
                  description: The name of the cursor scheme.
                cursorFiles:
                  type: object
                  description: A dictionary of cursor file names and their corresponding file paths.
      responses:
        '200':
          description: INF file generated successfully.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
